### PR TITLE
Restructure repository to contain the rc crate as well

### PR DESCRIPTION
**Pull request by mitsuhiko**
This changes the way the two crates are built so that it works for both released versions as well as git dependencies to the repository directly for both `im` and `im-rc`. Additionally it tests against the release versions of the crates, fixes the doctests referring to the wrong crate for the rc version and parallelizes the travis tests.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
The way this is structured now is a bit odd but it has reasons.

Inside the `rc` folder there is a single `Cargo.toml` which is more or less a copy of the one from the toplevel `Cargo.toml` just that it refers to all other files (readme, build, crate) by going up a folder. This means that if one adds a git dependency the `im-rc` crate can be found. This crate however cannot be published because it refers to files outside of its local tree.

For publishing the `assemble-releases.sh` file is provided. If run with `./assemble-releases.sh` it just puts the final crates into the `dist/$VERSION` folder (as `im` and `im-rc` respectively). When run with an optional argument it also changes the version number. Separately `./set-version.sh` exists which just bumps the version in the two cargo toml files. (I use perl for this because `sed` is not standardized enough and different on different platforms. The original commands did not work on mac for instance).

The tests in travis run against the built versions. This is done because `extern crate im` refers to the wrong one and the release versions run a replace for `im` to `im_rc` for the rc variation.

This now means that tests run agains the actual release versions and that includes the doctests. If one wants to use a git dependency (like I wanted) then this also works.

**Comment by mitsuhiko** [comment]
@bodil I could add a `Cargo.toml.in` file and then a script to generate `Cargo.toml` and `rc/Cargo.toml` out of that template. That way at least the process is automated.

**Comment by mitsuhiko** [comment]
@bodil I pushed up a version that uses m4 to generate out toml files. Not the most modern thing but pretty straightforward. This also adds a Makefile. `make release` should do the whole shebang, whereas `make update-toml` just updates the `Cargo.toml` and `rc/Cargo.toml` based on the `Cargo.toml.in` file.

**Comment by bodil** [comment]
uuuugh, I'm not keen on adding those dependencies even outside of the build phase. I'll just merge this - seems to work well - but I think I'm likely to rewrite the makefile stuff in Rust...

**Comment by bodil** [comment]
Thanks. :+1:

**Comment by mitsuhiko** [comment]
@bodil fwiw i picked m4 and perl because they are everywhere :)

**Comment by bodil** [comment]
I just tagged a new release, `make release` appears to work. :smile: https://crates.io/crates/im-rc

**Pull request merged**
